export type StudyRoom = {
	id: string;
	building: string;
	roomNumber: string;
	capacity: number;
	features: string[];
	floor: number;
	isQuiet: boolean;
	hasWhiteboard: boolean;
	hasMonitor: boolean;
};

export const STUDY_ROOMS: StudyRoom[] = [
	{
		id: "lib-101",
		building: "Main Library",
		roomNumber: "101",
		floor: 1,
		capacity: 4,
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
		features: ["quiet", "whiteboard", "individual study", "near coffee", "power outlets"],
	},
	{
		id: "lib-204",
		building: "Main Library",
		roomNumber: "204",
		floor: 2,
		capacity: 8,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
		features: ["group study", "whiteboard", "monitor", "video-capable", "near coffee"],
	},
	{
		id: "lib-310",
		building: "Main Library",
		roomNumber: "310",
		floor: 3,
		capacity: 2,
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: false,
		features: ["quiet", "individual study", "window", "low traffic"],
	},
	{
		id: "sci-115",
		building: "Science Center",
		roomNumber: "115",
		floor: 1,
		capacity: 6,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: false,
		features: ["group study", "whiteboard", "near lab", "power outlets"],
	},
	{
		id: "sci-220",
		building: "Science Center",
		roomNumber: "220",
		floor: 2,
		capacity: 10,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
		features: ["group study", "whiteboard", "monitor", "presentation-friendly", "movable tables"],
	},
	{
		id: "sci-305",
		building: "Science Center",
		roomNumber: "305",
		floor: 3,
		capacity: 3,
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: false,
		features: ["quiet", "whiteboard", "individual study", "low traffic"],
	},
	{
		id: "eng-140",
		building: "Engineering Hall",
		roomNumber: "140",
		floor: 1,
		capacity: 12,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
		features: ["group study", "whiteboard", "monitor", "near coffee", "collaboration space"],
	},
	{
		id: "eng-233",
		building: "Engineering Hall",
		roomNumber: "233",
		floor: 2,
		capacity: 6,
		isQuiet: true,
		hasWhiteboard: true,
		hasMonitor: true,
		features: ["quiet", "whiteboard", "monitor", "projector-ready", "power outlets"],
	},
	{
		id: "eng-410",
		building: "Engineering Hall",
		roomNumber: "410",
		floor: 4,
		capacity: 20,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
		features: ["group study", "whiteboard", "monitor", "presentation-friendly", "accessible"],
	},
	{
		id: "stu-028",
		building: "Student Union",
		roomNumber: "028",
		floor: 0,
		capacity: 5,
		isQuiet: false,
		hasWhiteboard: false,
		hasMonitor: true,
		features: ["monitor", "near coffee", "high traffic", "casual seating"],
	},
	{
		id: "stu-201",
		building: "Student Union",
		roomNumber: "201",
		floor: 2,
		capacity: 8,
		isQuiet: false,
		hasWhiteboard: true,
		hasMonitor: true,
		features: ["group study", "whiteboard", "monitor", "near coffee", "reservable"],
	},
	{
		id: "stu-315",
		building: "Student Union",
		roomNumber: "315",
		floor: 3,
		capacity: 2,
		isQuiet: true,
		hasWhiteboard: false,
		hasMonitor: false,
		features: ["quiet", "individual study", "window", "low traffic"],
	},
];
